### PR TITLE
W3c ccg2fhir example

### PR DESCRIPTION
**Pull request by mukundanps**
@tplooker Our proposal for w3c-ccg vocabulary updates based on our meeting on March 5th. John and I are happy to meet in order to review this with you and other SME's to move this forward.

**Purpose of this PR** 
The purpose of this PR is to demonstrate mapping of the w3c-ccg vaccination certificate vocabulary to the HL7 R4 FHIR resource model. This will facilitate reuse of existing mechanisms (e.g. SMART on FHIR), thus allowing interoperability with any EHR or healthcare application that can support the FHIR standard.

 Using FHIR resource model also helps in accurate and consistent handling of vaccination data in the context of jurisdictional requirements such as compliance, privacy by utilizing context specific data already available such as mapping between vaccine catalog & codes, manufacturers (e.g. CDC CVRS v2.5 mapping CVX to MVX and NDC codes, Canadian Vaccine Catalog etc). This will help in not only maintaining accuracy of the data, but also help with optimizing the representation size of vaccine certificates for QR codes etc.

**Background** 
We provide 2 examples in this PR showing how jurisdictional requirements affect the mapping from the FHIR resource model.

- EU Ehealth context maps the FHIR resource model (_Patient, Immunization and ImmunizationRecommendation_) to w3c-ccg vaccination certificate schema.
- CDC CVRS v2.5 context maps legacy HL7 v2 reporting format to FHIR resource model (_Patient, Immunization_), which is then mapped to w3c-ccg vaccination certificate schema. Example bundle file for this scenario (essentially an R4 mapping of CDC CVRS v2.5 spec) can be found [here](https://github.com/SemanticClarity/oca-fhir-cli/tree/master/examples/cdc-cvrs-v2.5).

In both cases, a FHIR Bundle resource type is assumed to be used as the container (resource) type that includes the necessary resources types such as FHIR Patient, Immunization etc required for this vocabulary mapping. Such a FHIR Bundle can be the result of:

- RESTful search operation on EHR with FHIR API support
- Part of a message exchange (e.g. health exchange use cases)
- Creating persistent and interoperable clinical documents

**Mapping overview**  
The mapping strategy demonstrated here is aimed at optimizing the representation size of the final vaccination certificate.   Context sensitive `@id` and `@type` mapping is utilized to map to the FHIR resource model. `@id` URI's do not resolve, but in this iteration, the intent is to show the specific FHIR resource/property to which the w3c-ccg vocabulary is mapped to.
E.g VaccineRecipient.birthDate is mapped to FHIR _Patient_ resource (_birthDate_ property). The `@id` mapping for this field is http://hl7.org/fhir/Patient.birthDate. (although not resolvable - 404 error, it makes the FHIR resource mapping clear) rather than use a resolvable url such as _https://www.hl7.org/fhir/patient-definitions.html#Patient.birthDate_.

Context sensitive `@type` mappings always point to a primitive data type such as integers or string values.

 FHIR resource models (both legacy HLv2 or R3, R4) extensively use value sets (e.g. coded values for gender, vaccines, roles etc) and code systems (e.g. SNOMEDCT codes for disorders, LOINC for Lab orders etc). The `@id` field (e.g. VaccinationEvent.vaccine) is mapped to existing HL7 value sets where appropriate. 

**Issues/Discussion points**

- Resolving http 404's on @id mappings to FHIR resource types (or use fhircat?)
- Unresolved definitions of valuesets/codes relevant to covid-19 e.g. CDC has published EUA - Emergency Usage Authorization value sets that may not exist in HL7 value sets as of this writing.The above could be resolved by incorporating these in w3c-ccg vocabulary as supporting artifacts.

### CODE REVIEW

**Comment by tplooker** [comment]
Thanks @mukundanps this looks like a great PR, because there is the SVIP plug-fest coming up next week I will hold off merging this until then.

> Resolving http 404's on @id mappings to FHIR resource types (or use fhircat?)

I believe our current approach keeps us inline with the FHIR cat project?

> Unresolved definitions of valuesets/codes relevant to covid-19 e.g. CDC has published EUA - Emergency Usage Authorization value sets that may not exist in HL7 value sets as of this writing.The above could be resolved by incorporating these in w3c-ccg vocabulary as supporting artifacts.

+1 I think we spoke briefly about this on our last call?

Just a quick note on the context files, any reason you have not added to the existing context file?

**Comment by mprorock** [comment]
Agree on hold merge, but this is great

**Review by mprorock — APPROVED** [review]

**Comment by mukundanps** [comment]
@tplooker Thanks for your feedback. You're correct. Our current approach in aligned with fhircat. We can adjust this once this issue is addressed by fhircat project.
 
On your other questions: 
  -Valuesets relevant to covid-19 emergency usage authorization (e.g. CDC) etc, you are correct. In this iteration we haven't added those to the context files. We can generate the jsonld version of a json (fhir) valueset, and use that as a reference table for each "jurisdictional" context file (locally hosted on w3c-ccg). 
   -Adding the context files to the existing context files: It seems that these context files are going to be used in a "mutually exclusive" manner. An example would be great. Are you thinking "inclusion" by jurisdiction (e.g. country code mapped to the appropriate context file?)

**Comment by mukundanps** [comment]
@mprorock Thanks for your feedback/approval

**Review by OR13 — APPROVED** [review]
Generally this looks good to me, I think ideally we would provide spec updates to cover HL7 / FHIR data conversion... something like input and output examples.

**Comment by mukundanps** [comment]
@OR13 Thanks for your feedback. Yes, we'll work with Tobias to formalize the spec updates. We do have 2 examples for different jurisdictional mappings, we will plan to include those.

**Comment by mukundanps** [comment]
@tplooker Based on our discussion yesterday, we propose two options:


- [Option 1] We delete one of the context files (cdc-cvrs), keep eu-ehealth fhir to w3c-ccg mapping. Perhaps rename this to _unstable/fhir-w3c-ccg-context.json_? This would help you do a quick validation of the simple fhir mapping (i.e we do not take _jurisdiction_ and _language_ in to account). So, you'll still start with just one context file/mapping and test out the basic idea.

- [Option 2]  This could be closer to a "stabler" option: we can leverage JSONLD id maps to structure the data by jurisdiction and language, even allowing different mapping to FHIR.  This would give us a stabler option of allowing for valueset's for vaccine codes, gender, practitioner roles etc to be localized to jurisdictional and language needs. We can provide some (covid-19) example json or jsonld documents for valuesets. This method will allow a single context file, however there will be bloat over time, making it hard to maintain. Where mapping from FHIR to W3C-CCG vocab varies by jurisdiction, this method would need to be applied within the global context of the vaccine schema. Here we have avoided changing your existing context.

```
"VaccinationEvent" :  ...
  "vaccine" : {
         "@id": "http://w3id.org/vaccination"

          "@context" : {
              "@base": "http://w3id.org/vaccination"
           },
          "@container": "@id" //or ["@id", "@set"],
          "US/en/cdc-cvrs-cvx-valueset": 207,
          "EU/en/eu-ehealth-vaccine-valueset": "xxx" 
      }
```

 In the example above, we map _vaccine_ to a different valueset for this jurisdiction, resulting in @id property for the "value" of the vaccine mapping to _http://w3id.org/vaccination/US/en/cdc-cvrs-cvx-valueset_ and _http://w3id.org/vaccination/US/en/eu-ehealth-vaccine-valueset_ . Since this is a standard JSONLD mechanism, we hope this would still work with BBS+ crypto w.r.t selective disclosure etc.

**Review by tplooker — APPROVED** [review]

**Comment by tplooker** [comment]
As discussed on a call with @mukundanps recently we have resolved to merge this as a new unstable context to experiment without breaking the existing definition

**Comment by tplooker** [comment]
Thanks @mukundanps for the PR!

**Review by tplooker — APPROVED** [review]

**Pull request merged**
